F=

.PHONY: t
t: .db
	mix test ${F}

.PHONY:
db:
	rm -f .db
	$(MAKE) --no-print-directory .db

.db:
	psql -q -x -U root -h 127.0.0.1  -p 26257 -c "drop database if exists roachfeed_test"
	psql -q -x -U root -h 127.0.0.1  -p 26257 -c "create database roachfeed_test"
	echo "generated by make" > .db

